INSERT INTO clienti (nome, cognome, carta_id, email, telefono)
VALUES (
                'Bob',
                'Aggiustatutto',
                'BY9213F',
                'bobby@email.com',
                '555-3994'
        ),
        (
                'Alice',
                'Rossi',
                'AR1234G',
                'alice@email.com',
                '555-5678'
        ),
        (
                'John',
                'Smith',
                'JS5678H',
                'john@email.com',
                '555-1234'
        ),
        (
                'Emily',
                'Johnson',
                'EJ2345I',
                'emily@email.com',
                '555-7890'
        ),
        (
                'Michael',
                'Brown',
                'MB6789J',
                'michael@email.com',
                '555-4567'
        ),
        (
                'Sophia',
                'Lee',
                'SL3456K',
                'sophia@email.com',
                '555-2345'
        ),
        (
                'William',
                'Davis',
                'WD7890L',
                'william@email.com',
                '555-8901'
        ),
        (
                'Olivia',
                'Garcia',
                'OG4567M',
                'olivia@email.com',
                '555-6789'
        ),
        (
                'James',
                'Martinez',
                'JM8901N',
                'james@email.com',
                '555-3456'
        ),
        (
                'Ava',
                'Lopez',
                'AL1234O',
                'ava@email.com',
                '555-6789'
        ),
        (
                'Benjamin',
                'Hall',
                'BH2345P',
                'benjamin@email.com',
                '555-1234'
        ),
        (
                'Ella',
                'Hernandez',
                'EH5678Q',
                'ella@email.com',
                '555-4567'
        ),
        (
                'Daniel',
                'Young',
                'DY3456R',
                'daniel@email.com',
                '555-8901'
        ),
        (
                'Mia',
                'King',
                'MK6789S',
                'mia@email.com',
                '555-2345'
        ),
        (
                'Logan',
                'Adams',
                'LA4567T',
                'logan@email.com',
                '555-6789'
        ),
        (
                'Grace',
                'Campbell',
                'GC7890U',
                'grace@email.com',
                '555-1234'
        ),
        (
                'Liam',
                'Turner',
                'LT1234V',
                'liam@email.com',
                '555-4567'
        );